### Task 1: Perform basic operations using Tensorflow (Defining constants, variables, concatenation, add, multiply, reduce mean, reduce sum)

<table style="border: 1px solid black; border-collapse: collapse;" cellpadding="5">
  <tr>
    <td style="border: 1px solid black;"><strong>Roll No:</strong> A018</td>
    <td style="border: 1px solid black;"><strong>Name:</strong> Dhruv Thanawala</td>
  </tr>
  <tr>
    <td style="border: 1px solid black;"><strong>Class:</strong> BTech IT</td>
    <td style="border: 1px solid black;"><strong>Batch:</strong> A1</td>
  </tr>
  <tr>
    <td style="border: 1px solid black;"><strong>Date of Experiment:</strong> 15<sup>th</sup> July, 2025</td>
    <td style="border: 1px solid black;"><strong>Date of Submission:</strong> 15<sup>th</sup> July, 2025</td>
  </tr>
</table>


In [3]:
import tensorflow as tf
import numpy as np

## 1. Constants

In [6]:
scalar_constant = tf.constant(5.0)
vector_constant = tf.constant([1, 2, 3, 4])
matrix_constant = tf.constant([[1, 2], [3, 4]])

In [10]:
print("Scalar constant:", scalar_constant.numpy())
print("Vector constant:", vector_constant.numpy())
print("Matrix constant:", matrix_constant.numpy())

Scalar constant: 5.0
Vector constant: [1 2 3 4]
Matrix constant: [[1 2]
 [3 4]]


## 2. Variables

In [12]:
scalar_var = tf.Variable(10.0)
vector_var = tf.Variable([1, 2, 3, 4])
matrix_var = tf.Variable([[1, 2], [3, 4]])

In [13]:
print("Scalar variable:", scalar_var.numpy())
print("Vector variable:", vector_var.numpy())
print("Matrix variable:", matrix_var.numpy())

Scalar variable: 10.0
Vector variable: [1 2 3 4]
Matrix variable: [[1 2]
 [3 4]]


## 3. Operations

In [14]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
c = tf.constant(10)

In [15]:
# Vector addition
add_vectors = tf.add(a, b)
print(f"Vector addition: {a} + {b} = {add_vectors}")

Vector addition: [1 2 3] + [4 5 6] = [5 7 9]


In [16]:
# Scalar addition
add_scalar = tf.add(c, 5)
print(f"Scalar addition: {c} + 5 = {add_scalar}")

Scalar addition: 10 + 5 = 15


In [20]:
# Broadcasting addition
broadcast_add = tf.add(a, c)
print(f"Broadcasting addition: {a} + {c} = {broadcast_add}")

Broadcasting addition: [1 2 3] + 10 = [11 12 13]


In [21]:
mat1 = tf.constant([[1, 2], [3, 4]])
mat2 = tf.constant([[5, 6], [7, 8]])

In [22]:
# Matrix Addition
add_matrices = tf.add(mat1, mat2)
print(f"Matrix addition:\n{mat1}\n+\n{mat2}\n=\n{add_matrices}")

Matrix addition:
[[1 2]
 [3 4]]
+
[[5 6]
 [7 8]]
=
[[ 6  8]
 [10 12]]


In [23]:
# Element-wise multiplication
mult_vectors = tf.multiply(a, b)
print(f"Element-wise multiplication: {a} * {b} = {mult_vectors}")

Element-wise multiplication: [1 2 3] * [4 5 6] = [ 4 10 18]


In [24]:
# Scalar multiplication
mult_scalar = tf.multiply(a, c)
print(f"Scalar multiplication: {a} * {c} = {mult_scalar}")

Scalar multiplication: [1 2 3] * 10 = [10 20 30]


In [26]:
# Matrix multiplication
mat_mult = tf.matmul(mat1, mat2)
print(f"Matrix multiplication:\n{mat1}\n*\n{mat2}\n=\n{mat_mult}")

Matrix multiplication:
[[1 2]
 [3 4]]
*
[[5 6]
 [7 8]]
=
[[19 22]
 [43 50]]


In [27]:
vec1 = tf.constant([1, 2, 3])
vec2 = tf.constant([4, 5, 6])

In [30]:
# Vector Concatenation
concat_vectors = tf.concat([vec1, vec2], axis=0)
print(f"Vector concatenation: {vec1} + {vec2} = {concat_vectors}")

Vector concatenation: [1 2 3] + [4 5 6] = [1 2 3 4 5 6]


In [31]:
# Matrix concatenation along axis 0 (rows)
mat_a = tf.constant([[1, 2], [3, 4]])
mat_b = tf.constant([[5, 6], [7, 8]])
concat_rows = tf.concat([mat_a, mat_b], axis=0)
print(f"Matrix concatenation (rows):\n{concat_rows}")

Matrix concatenation (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [32]:
# Matrix concatenation along axis 1 (columns)
concat_cols = tf.concat([mat_a, mat_b], axis=1)
print(f"Matrix concatenation (columns):\n{concat_cols}")

Matrix concatenation (columns):
[[1 2 5 6]
 [3 4 7 8]]


In [33]:
# 3D tensor concatenation
tensor_3d_1 = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor_3d_2 = tf.constant([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
concat_3d = tf.concat([tensor_3d_1, tensor_3d_2], axis=0)
print(f"3D tensor concatenation shape: {concat_3d.shape}")

3D tensor concatenation shape: (4, 2, 2)


In [34]:
# Vector mean
numbers = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])
mean_all = tf.reduce_mean(numbers)
print(f"Mean of {numbers}: {mean_all}")

Mean of [1. 2. 3. 4. 5.]: 3.0


In [35]:
# Matrix mean
matrix = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
mean_all_matrix = tf.reduce_mean(matrix)
print(f"Mean of entire matrix: {mean_all_matrix}")

Mean of entire matrix: 3.5


In [36]:
# Mean along axis 0 (columns)
mean_axis0 = tf.reduce_mean(matrix, axis=0)
print(f"Mean along axis 0 (columns): {mean_axis0}")

Mean along axis 0 (columns): [2.5 3.5 4.5]


In [37]:
# Mean along axis 1 (rows)
mean_axis1 = tf.reduce_mean(matrix, axis=1)
print(f"Mean along axis 1 (rows): {mean_axis1}")

Mean along axis 1 (rows): [2. 5.]


In [38]:
# 3D tensor mean
tensor_3d = tf.constant([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])
mean_3d_all = tf.reduce_mean(tensor_3d)
mean_3d_axis0 = tf.reduce_mean(tensor_3d, axis=0)
print(f"3D tensor mean (all): {mean_3d_all}")
print(f"3D tensor mean (axis 0): {mean_3d_axis0}")

3D tensor mean (all): 4.5
3D tensor mean (axis 0): [[3. 4.]
 [5. 6.]]


In [39]:
# Vector sum
sum_all = tf.reduce_sum(numbers)
print(f"Sum of {numbers}: {sum_all}")

Sum of [1. 2. 3. 4. 5.]: 15.0


In [40]:
# Matrix sum
sum_all_matrix = tf.reduce_sum(matrix)
print(f"Sum of entire matrix: {sum_all_matrix}")

Sum of entire matrix: 21.0


In [41]:
# Sum along axis 0 (columns)
sum_axis0 = tf.reduce_sum(matrix, axis=0)
print(f"Sum along axis 0 (columns): {sum_axis0}")

Sum along axis 0 (columns): [5. 7. 9.]


In [42]:
# Sum along axis 1 (rows)
sum_axis1 = tf.reduce_sum(matrix, axis=1)
print(f"Sum along axis 1 (rows): {sum_axis1}")

Sum along axis 1 (rows): [ 6. 15.]


In [43]:
# Keep dimensions
sum_keepdims = tf.reduce_sum(matrix, axis=1, keepdims=True)
print(f"Sum with keepdims: {sum_keepdims}")

Sum with keepdims: [[ 6.]
 [15.]]
