### Task 2: Perform linear algebra operations using Tensorflow (transpose, matrix multiplication, elementwise multiplication, determinant)

<table style="border: 1px solid black; border-collapse: collapse;" cellpadding="5">
  <tr>
    <td style="border: 1px solid black;"><strong>Roll No:</strong> A018</td>
    <td style="border: 1px solid black;"><strong>Name:</strong> Dhruv Thanawala</td>
  </tr>
  <tr>
    <td style="border: 1px solid black;"><strong>Class:</strong> BTech IT</td>
    <td style="border: 1px solid black;"><strong>Batch:</strong> A1</td>
  </tr>
  <tr>
    <td style="border: 1px solid black;"><strong>Date of Experiment:</strong> 15<sup>th</sup> July, 2025</td>
    <td style="border: 1px solid black;"><strong>Date of Submission:</strong> 15<sup>th</sup> July, 2025</td>
  </tr>
</table>


In [2]:
import tensorflow as tf

In [4]:
A = tf.constant([[1, 2, 3], 
                 [4, 5, 6]], dtype=tf.float32)

B = tf.constant([[1, 2], 
                 [3, 4], 
                 [5, 6]], dtype=tf.float32)

C = tf.constant([[2, 0], 
                 [1, 3]], dtype=tf.float32)

In [5]:
print("Matrix A:")
print(A)
print("Shape:", A.shape)

print("\nMatrix B:")
print(B)
print("Shape:", B.shape)

print("\nMatrix C:")
print(C)
print("Shape:", C.shape)

Matrix A:
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
Shape: (2, 3)

Matrix B:
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)
Shape: (3, 2)

Matrix C:
tf.Tensor(
[[2. 0.]
 [1. 3.]], shape=(2, 2), dtype=float32)
Shape: (2, 2)


In [6]:
# 1. TRANSPOSE
A_transpose = tf.transpose(A)
B_transpose = tf.transpose(B)

print("A transpose:")
print(A_transpose)
print("Shape:", A_transpose.shape)

A transpose:
tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)
Shape: (3, 2)


In [7]:
# 2. MATRIX MULTIPLICATION
AB = tf.matmul(A, B)
print("A @ B:")
print(AB)
print("Shape:", AB.shape)

A @ B:
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)
Shape: (2, 2)


In [8]:
# 3. ELEMENT-WISE MULTIPLICATION

# Create matrices of same shape for element-wise multiplication
D = tf.constant([[1, 2], 
                 [3, 4]], dtype=tf.float32)

E = tf.constant([[5, 6], 
                 [7, 8]], dtype=tf.float32)

DE_elementwise = tf.multiply(D, E)
print("\nD * E (element-wise):")
print(DE_elementwise)


D * E (element-wise):
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)


In [10]:
# 4. DETERMINANT
# Determinant works only on square matrices
det_C = tf.linalg.det(C)
print("Determinant of C:")
print(det_C.numpy())

det_D = tf.linalg.det(D)
print("\nDeterminant of D:")
print(det_D.numpy())

Determinant of C:
6.0

Determinant of D:
-2.0


In [12]:
F = tf.constant([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 10]], dtype=tf.float32)

print("\nMatrix F:")
print(F.numpy())

det_F = tf.linalg.det(F)
print("Determinant of F:")
print(det_F.numpy())



Matrix F:
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 10.]]
Determinant of F:
-2.9999986
